// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0e91iDSSN-CEvKlqNnfcBAu-q56a8M88',
    appId: '1:960875369229:web:3892312ae7bd95cae25644',
    messagingSenderId: '960875369229',
    projectId: 'cohortly-22739',
    authDomain: 'cohortly-22739.firebaseapp.com',
    storageBucket: 'cohortly-22739.appspot.com',
    measurementId: 'G-Z8JF9R143N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbz4yd17halBHUdYYXooTld9BYEbPZksk',
    appId: '1:960875369229:android:150ec580ac5cdd8ce25644',
    messagingSenderId: '960875369229',
    projectId: 'cohortly-22739',
    storageBucket: 'cohortly-22739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTqNmby4eUKaz9pG48THDtBezBhmHjgU',
    appId: '1:960875369229:ios:c68ffb4042afa99ae25644',
    messagingSenderId: '960875369229',
    projectId: 'cohortly-22739',
    storageBucket: 'cohortly-22739.appspot.com',
    iosBundleId: 'com.example.cohortly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADTqNmby4eUKaz9pG48THDtBezBhmHjgU',
    appId: '1:960875369229:ios:d62b3ee0f6b9c61fe25644',
    messagingSenderId: '960875369229',
    projectId: 'cohortly-22739',
    storageBucket: 'cohortly-22739.appspot.com',
    iosBundleId: 'com.example.cohortly.RunnerTests',
  );
}
